### ISSUE TITLE
Normalization error in srsf_to_f

### ISSUE THREAD

**Issue by Almond-S** [jdtuck/fdasrvf_R#2]
Hi,

thank you for that nice R package! 
However, I found a certain issue in the code of the function `srsf_to_f`:

The norm of the sqv-function in the multidimensional case is defined as `qnorm = abs(q[, i])` , which must be `qnorm = sqrt(crossprod(q[, i]))`.

Best,
Almond

**Comment by jdtuck** [comment]
What do you mean by multidimensional, that is for functional data which is not multidimensional

**Comment by jdtuck** [comment]
For curves (multidimensional) you want srvf_to_f, which I have not exposed, I will add that

**Comment by Almond-S** [comment]
Oh yes, I see, I didn't expect that there's another function q_to_curve for the multidimensional case. 
Thank you!

**Comment by jdtuck** [comment]
No problem and thanks for asking questions :-)
