### ISSUE TITLE
C++11 requirement

### ISSUE THREAD

**Issue by astamm** [jdtuck/fdasrvf_R#22]
In the next `R 4.3.0` version, CRAN will request that any package requiring C++ in the `SystemRequirements` entry of the `DESCRIPTION` file defaults to `C++17`. There are two ways of handling this. If your package does not actually use syntax from either `C++11` of `C++14` or `C++17`, then we could remove the requirement completely as it is currently being done for many **tidyverse**-related packages or **Rcpp**-related packages.
Otherwise we will need to update to `C++17`.

**Comment by jdtuck** [comment]
This has been solved on master
