### ISSUE TITLE
mode = "C" doesn't work in clac_shape_dist

### ISSUE THREAD

**Issue by gjm112** [jdtuck/fdasrvf_R#28]
The following code doesn't work for me: 
librayr(fdasrvf)
out <- calc_shape_dist(beta[, , 1, 1], beta[, , 1, 4], mode = "C")

Error in f[, (tau + 1):T1] : subscript out of bounds

mode = "O" works fine, but mode = "C" gives me that error.

**Comment by jdtuck** [comment]
Thank you, please use latest version on github as this has been fixed
