### ISSUE TITLE
Distance computation in `find_rotation_seed_*()` functions

### ISSUE THREAD

**Issue by astamm** [jdtuck/fdasrvf_R#41]
I believe the `dist` object created here 
https://github.com/jdtuck/fdasrvf_R/blob/97fe21c871996579965c34dcf9a14e24698099ce/R/curve_functions.R#L215-L217
is only between -1 and 1 if `scale=TRUE`.
Indeed `q1` and `q2new` are not of norm 1 unless `scale` has been set to `TRUE`.

**Comment by jdtuck** [comment]
yes given the current changes that would be correct

**Comment by astamm** [comment]
The fix is easy in `calc_shape_dist()` but what should be done for `Ec` in `find_rotation_seed_*()` when `scale` is `FALSE`? Should we use $L^2$ geometry in these cases?

**Comment by jdtuck** [comment]
Yes we should use that geometry, it really only matters for closed curves as the loop is executed once for open curves.
