### ISSUE TITLE
Distance computation in `find_rotation_seed_unqiue()`

### ISSUE THREAD

**Issue by astamm** [jdtuck/fdasrvf_R#42]
I wanted to fix this function as I did with `find_rotation_seed_coord()` using the $L^2$ geometry when `scale=FALSE` but it seems that function does not use the `scale` argument.

This makes sense as it expects the SRVFs as input. But that makes the choice of the geometry difficult here.

One could say that the `scale` argument in this function has the meaning of saying that the input SRVFs have already been scaled or not. But that would give the `scale` argument a totally different meaning w.r.t. all other functions.

Another possibility would be to systematically scale the SRVFs and always use $\mathbb{S}_\infty$ geometry but that would imply that this function can only be used for analysis in this specific preshape space and not in $L^2$.

Currently, I am seeing this:
https://github.com/jdtuck/fdasrvf_R/blob/c9bf800184e7e842488d675af5eedd1e93c018d6/R/curve_functions.R#L295-L302
which uses the metric on $\mathbb{S}_\infty$ but computed between `q1` and `q2new` that might not necessarily be scaled beforehand by the user.

That being said, this is not a function exposed to users so maybe you are already using it exclusively when you know that the input SRVFs are scaled.

How would you like to handle this if there is anything to be handled?

**Comment by astamm** [comment]
Oooh and silly side question: is `unquie` in the function name a typo for `unique`? If not, what does it mean?

**Comment by jdtuck** [comment]
Yes that is a typo

**Comment by astamm** [comment]
Ok I am fixing this. Would that make sense to add the `lam` parameter to `find_rotation_seed_coord()` as well?

**Comment by jdtuck** [comment]
Yes for future.

**Comment by astamm** [comment]
Ok. If I want to improve documentation about `lambda`, is it the weight go a penalty term to avoid over-alignment?

**Comment by jdtuck** [comment]
It’s the weight on the penalty term to restrict how far gamma can get from gamma_id. I do not like the term “over alignment” as there is not agreement on what that actually means.

**Comment by astamm** [comment]
I am comparing `find_rotation_seed_coord()` and `find_rotation_seed_unique()` more in depth. In addition to the fact that the former expects curves while the latter expects SRVFs, I also see that 

- `find_best_rotation()` is applied on curves in the former while on SRVFs on the latter. Can't that change the estimated rotation?
- the former also outputs the `beta2n` curve which is properly scaled when `scale=TRUE`
- `shift_f()` is applied on on curves in the former while on SRVFs on the latter. Can't that change the estimated shift?
- to apply the optimal reparametrization, `find_rotation_seed_unique()` also uses `group_action_by_gamma_coord()` which forces to use `q_to_curve()`. I see that there is a function called `group_action_by_gamma()`. Does that directly apply to the SRVF? If so, shouldn't we use that?
- `project_curve()` for closed curves is always applied on SRVFs but in the case of `find_rotation_seed_coord()`, the `beta2new` curve is not updated accordingly. Should it be the case?

**Comment by astamm** [comment]
Digging into `find_best_rotation()`, given the name of the two inputs, I infer it should apply only to SRVFs which would suggest to fix `find_rotation_seed_coord()`.

Digging into `group_action_by_gamma()`, it seems indeed to be the reparametrization applied to the SRVF, which could thus be used instead of `group_action_by_gamma_coord()` in `find_rotation_seed_unique()`. However, we should add a `scale` argument to `group_action_by_gamma()` to choose whether to normalise the output. Currently normalisation is enforced.

**Comment by jdtuck** [comment]
> I am comparing `find_rotation_seed_coord()` and `find_rotation_seed_unique()` more in depth. In addition to the fact that the former expects curves while the latter expects SRVFs, I also see that
> 
> * `find_best_rotation()` is applied on curves in the former while on SRVFs on the latter. Can't that change the estimated rotation?

No

> * the former also outputs the `beta2n` curve which is properly scaled when `scale=TRUE`
> * `shift_f()` is applied on on curves in the former while on SRVFs on the latter. Can't that change the estimated shift?

No

> * to apply the optimal reparametrization, `find_rotation_seed_unique()` also uses `group_action_by_gamma_coord()` which forces to use `q_to_curve()`. I see that there is a function called `group_action_by_gamma()`. Does that directly apply to the SRVF? If so, shouldn't we use that?

`group_action_by_gamma_coord` is for curves, `group_action_by_gamma` is for SRVFS, we can use that. The current way is fine or you can use `group_action_by_gamma`. 

> * `project_curve()` for closed curves is always applied on SRVFs but in the case of `find_rotation_seed_coord()`, the `beta2new` curve is not updated accordingly. Should it be the case?

Yes

**Comment by jdtuck** [comment]
> Digging into `find_best_rotation()`, given the name of the two inputs, I infer it should apply only to SRVFs which would suggest to fix `find_rotation_seed_coord()`.

No it can take either curves or srvfs

> 
> Digging into `group_action_by_gamma()`, it seems indeed to be the reparametrization applied to the SRVF, which could thus be used instead of `group_action_by_gamma_coord()` in `find_rotation_seed_unique()`. However, we should add a `scale` argument to `group_action_by_gamma()` to choose whether to normalise the output. Currently normalisation is enforced.

For the action this would be fine

**Comment by astamm** [comment]
Thanks for the answers.

> `group_action_by_gamma_coord` is for curves, `group_action_by_gamma` is for SRVFS, we can use that. The current way is fine or you can use `group_action_by_gamma`.

I know it is currently doing the right thing but at the cost of calling one more time `q_to_curve()` within `find_rotation_seed_unique()` while I think the whole purpose of this function is to manipulate SRVFs and never work in the space of curves.

**Comment by astamm** [comment]
> * `project_curve()` for closed curves is always applied on SRVFs but in the case of `find_rotation_seed_coord()`, the `beta2new` curve is not updated accordingly. Should it be the case?

I'll fix that.
