### ISSUE TITLE
Symmetry property of `calc_shape_dist()`

### ISSUE THREAD

**Issue by astamm** [jdtuck/fdasrvf_R#46]
If I do

```r
library(fdasrvf)
calc_shape_dist(beta[, , 1, 1], beta[, , 1, 4])$d
calc_shape_dist(beta[, , 1, 4], beta[, , 1, 1])$d
```

I get two different geodesic distances, meaning that $d(f_1, f_2) != d(f_2, f_1)$.
Is that explained by numerical issues, or is there something wrong in the current implementation?

**Comment by astamm** [comment]
Specifically,

```r
# Basic L2 distance
calc_shape_dist(beta[, , 1, 1], beta[, , 1, 4], 
                alignment = FALSE, 
                rotation = FALSE, 
                scale = FALSE)$d
calc_shape_dist(beta[, , 1, 4], beta[, , 1, 1], 
                alignment = FALSE, 
                rotation = FALSE, 
                scale = FALSE)$d
# OK

# With alignment
calc_shape_dist(beta[, , 1, 1], beta[, , 1, 4], 
                alignment = TRUE, 
                rotation = FALSE, 
                scale = FALSE)$d
calc_shape_dist(beta[, , 1, 4], beta[, , 1, 1], 
                alignment = TRUE, 
                rotation = FALSE, 
                scale = FALSE)$d
# NOT OK

# With rotation invariance
calc_shape_dist(beta[, , 1, 1], beta[, , 1, 4], 
                alignment = FALSE, 
                rotation = TRUE, 
                scale = FALSE)$d
calc_shape_dist(beta[, , 1, 4], beta[, , 1, 1], 
                alignment = FALSE, 
                rotation = TRUE, 
                scale = FALSE)$d
# OK

# With alignment
calc_shape_dist(beta[, , 1, 1], beta[, , 1, 4], 
                alignment = FALSE, 
                rotation = FALSE, 
                scale = TRUE)$d
calc_shape_dist(beta[, , 1, 4], beta[, , 1, 1], 
                alignment = FALSE, 
                rotation = FALSE, 
                scale = TRUE)$d
# OK
```

Hence, alignment seems to be the issue here.

**Comment by jdtuck** [comment]
How far off, need to see numbers

**Comment by astamm** [comment]
You can run these pieces of code but it is not negligible. Not on my computer right now...

**Comment by jdtuck** [comment]
Exactly what are you getting on your computer, I need to compare to what I am getting which is ok.

**Comment by astamm** [comment]
From what I recall, for the cases I commented as OK, values were equal up to 4 digits. 

With alignment on, values differed at the second digit already.

**Comment by astamm** [comment]
```r
> calc_shape_dist(beta[, , 1, 1], beta[, , 1, 4], alignment = FALSE, rotation = FALSE, scale = FALSE)$d
[1] 29.05462
> calc_shape_dist(beta[, , 1, 4], beta[, , 1, 1], alignment = FALSE, rotation = FALSE, scale = FALSE)$d
[1] 29.05462
> calc_shape_dist(beta[, , 1, 1], beta[, , 1, 4], 
+                 alignment = TRUE, 
+                 rotation = FALSE, 
+                 scale = FALSE)$d
[1] 12.25834
> calc_shape_dist(beta[, , 1, 4], beta[, , 1, 1], 
+                 alignment = TRUE, 
+                 rotation = FALSE, 
+                 scale = FALSE)$d
[1] 16.05389
> # With rotation invariance
> calc_shape_dist(beta[, , 1, 1], beta[, , 1, 4], 
+                 alignment = FALSE, 
+                 rotation = TRUE, 
+                 scale = FALSE)$d
[1] 28.87555
> calc_shape_dist(beta[, , 1, 4], beta[, , 1, 1], 
+                 alignment = FALSE, 
+                 rotation = TRUE, 
+                 scale = FALSE)$d
[1] 28.87555
> # With alignment
> calc_shape_dist(beta[, , 1, 1], beta[, , 1, 4], 
+                 alignment = FALSE, 
+                 rotation = FALSE, 
+                 scale = TRUE)$d
[1] 0.8411584
> calc_shape_dist(beta[, , 1, 4], beta[, , 1, 1], 
+                 alignment = FALSE, 
+                 rotation = FALSE, 
+                 scale = TRUE)$d
[1] 0.8411584
```

As you can see the difference when alignment is on is huge.

**Comment by astamm** [comment]
After playing around a bit, I found that the guilty function is `DPQ()`, which estimates a different warping when aligning one curve to another or the other way around (comparing one to `invertGamma` of the other of course). When I use instead `DPQ2()`, warpings are the same.

That being said, I do not know the difference between both functions. I notice though that `DPQ2()` is the default over `DPQ()` in `optimum.reparam()`. But again, this is a function tailored for 1D functions, so maybe `DPQ2()` is not appropriate for general curves?

In any case, it provides symmetry in the estimated warping whereas `DPQ()` does not.

**Comment by astamm** [comment]
There is one argument in `DPQ2()` which is the dimension of the curves which leads me to think that the algorithm can be applied in dimensions greater than 1.

**Comment by astamm** [comment]
In addition to the error induced by the algorithm that searches the optimal warping, there is independently the problem that

$$
d(q_1 \circ \gamma, q_2 \circ \gamma) \ne d(q_1, q_2)
$$

and this is related to #44. In particular, the equality holds if I use representations of warpings and SRVFs as R functions.

**Comment by jdtuck** [comment]
`DPQ2` is a newer more accurate algorithm that has a the ability to adjust the grid size and the grid is more refined. Yes it works on multidimensional and we can swap it out. I am concerned why `DP` is not working well and will dig into that when I have time.

**Comment by astamm** [comment]
Thanks. I see `nbhd_dim Number of points in each grid axis.` in `DPQ2` which, in `optimum.reparam()` for instance, is set by default to `7L`. Do you have any guidelines about how to fix it, or is the default a *good* value in general?

**Comment by jdtuck** [comment]
The default of 7 is good. I will work on getting you the inputs, but don't have time as I leaving on travel in a few minutes.

**Comment by astamm** [comment]
Thanks. I wondered if `nbhd_dim` should somehow depends on the size of the grids (which I believe are `T1` and `T2`.
Safe travels!

**Comment by jdtuck** [comment]
It could, but does increase computational time by a lot, so it's a balance.
