### ISSUE TITLE
elastic.regression function

### ISSUE THREAD

**Issue by ajw11** [jdtuck/fdasrvf_R#48]
Good morning,

I have loaded the package 'fdasrvf' and would like to use elastic.regression. However, it does not appear that this function is exported when I load 'fdasrvf'. I looked in the source code here https://rdrr.io/cran/fdasrvf/src/R/elastic_regression.R and tried to piece the function together. However, there are some issues. For example, in the function regression_warp, there is this:

 if (y > alpha + y_M){
    gamma_new = gam_M
  }else if (y < alpha + y_m){
    gamma_new - gam_m
  }else{
    gamma_new = zero_crossing(y-alpha, q, beta, time, y_M, y_m, gam_M, gam_m)
  }

Shouldn't "gamma_new - gam_m" be "gamma_new =gam_m"? 

Also, I was wondering if the elastic.regression source code is the same that was used to produce experimental results 5.1.3 (pg. 79) in https://diginole.lib.fsu.edu/islandora/object/fsu:254513/datastream/PDF/view?

**Comment by jdtuck** [comment]
its not exported as there is theoretical problems with that method, additionally it is in a broken state. If you are needing a regression method, please use the pcr version.
