### ISSUE TITLE
 elastic.pcr.regression question

### ISSUE THREAD

**Issue by ajw11** [jdtuck/fdasrvf_R#49]
Good morning,

After looking at the source code for elastic.pcr.regression, I noted that the coefficients produced from the function vertFPCA are used as the predictor variables $x$ for OLS. In vertFPCA source code, these coefficients are produced here:

c[i,k] = sum((c(qn[,i],m_new[i])-mqn)*U[,k])

So each coefficient is an inner product of the mean centered ($\tilde{q}_i$, f(0)) and the respective eigenfunction. 

My question is that in this paper (https://arxiv.org/pdf/1805.11456) there is Equation (3.9) that says the coefficients are the inner product of $x_i(t)$ and $\xi_j(t)$, where $x_i(t)$ is from Table 1, which only has $\tilde{q}$, nothing about the intercept $f(0)$. It is correct to include the intercept $f(0)$ for elastic functional pc regression, right?

**Comment by jdtuck** [comment]
You include the intercept if you want to integrate back to the f-domain at some point. So yes it is correct
