### ISSUE TITLE
Estimated `curve_karcher_mean()` just replicates first curve in dataset

### ISSUE THREAD

**Issue by mpff** [jdtuck/fdasrvf_R#54]
Heya,

I have a bug in the mean estimation for 2d curves. It seems like the estimated means are just equal to the first curve in the dataset. Here is an example with two curves, where the means look exactly like the first curve in the dataset, when permuting the curves.

I saw that the first curve in the dataset seems to be used as an initial starting point for mean estimation. It seems like the mean somehow does not get updated in the following iterations?

```
out <- curve_karcher_mean(beta[, , 1, 1:2], maxit = 200)
out2 <- curve_karcher_mean(beta[, , 1, 2:1], maxit = 200)

par(mfrow=c(1,2))
plot(t(beta[,,1,1]), t = "l", asp = 1, main = "dataset of two curves")
lines(t(beta[,,1,2]), lty = "dashed", t = "l", col = 2)
plot(t(out$betamean), t = "l", main = "means are equal to respective 1st curve", asp = 1)
lines(t(out2$betamean), lty = "dashed", col = 2)
```

**Comment by jdtuck** [comment]
Why would you only use two samples to generate a mean?

**Comment by mpff** [comment]
I used two curves to illustrate the point in the example code. I think the issue persists in when using more curves though?

```
out <- curve_karcher_mean(beta[, , 1, 1:20], maxit = 200)
out2 <- curve_karcher_mean(beta[, , 1, 20:1], maxit = 200)

par(mfrow=c(1,2))
plot(t(beta[,,1,1]), t = "l", asp = 1, main = "first curves in dataset")
lines(t(beta[,,1,20]), lty = "dashed", t = "l", col = 2)
plot(t(out$betamean), t = "l", main = "means", asp = 1)
lines(t(out2$betamean), lty = "dashed", col = 2)
```

![05380635-007a-431f-8f43-50b9dd8ae52a](https://github.com/user-attachments/assets/79ec3238-432e-423f-8dc1-84189ac940d0)

**Comment by jdtuck** [comment]
@astamm these stem from your changes can you look into it

**Comment by jdtuck** [comment]
There was an initialization error added in the 2.0 release which has been removed on master.

**Comment by astamm** [comment]
@jdtuck Should I still investigate something here or is it all set?

**Comment by jdtuck** [comment]
All set
